openapi: 3.0.3
info:
    title: User API
    version: 1.0.0
paths: {}
components:
    schemas:
        GetUser:
            type: object
            required:
                - id
                - email
                - name
            properties:
                id:
                    type: string
                    format: uuid
                    description: The unique identifier of the user
                    example: "550e8400-e29b-41d4-a716-446655440000"
                email:
                    type: string
                    format: email
                    description: The email address of the user
                    example: "user@example.com"
                name:
                    type: string
                    description: The name of the user
                    example: "John Doe"
