FROM golang:1.25 as build

WORKDIR /build

COPY go.mod go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -buildvcs=false -o ./bin/worker ./cmd/worker

FROM alpine:3.18

RUN apk add --no-cache ca-certificates

COPY --from=build /build/bin/worker /usr/bin/worker

ENV REDIS_HOST=localhost
ENV REDIS_PORT=6379
ENV ASYNQ_ENABLED=true
ENV ASYNQ_CONCURRENCY=10

CMD ["/usr/bin/worker"]
