// Code generated by MockGen. DO NOT EDIT.
// Source: backend/repository/interfaces/email.repository_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/kamil5b/clean-go-vite-react/backend/model/entity"
)

// MockEmailRepository is a mock of EmailRepository interface.
type MockEmailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailRepositoryMockRecorder
}

// MockEmailRepositoryMockRecorder is the mock recorder for MockEmailRepository.
type MockEmailRepositoryMockRecorder struct {
	mock *MockEmailRepository
}

// NewMockEmailRepository creates a new mock instance.
func NewMockEmailRepository(ctrl *gomock.Controller) *MockEmailRepository {
	mock := &MockEmailRepository{ctrl: ctrl}
	mock.recorder = &MockEmailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailRepository) EXPECT() *MockEmailRepositoryMockRecorder {
	return m.recorder
}

// GetEmailLog mocks base method.
func (m *MockEmailRepository) GetEmailLog(ctx context.Context, id string) (*entity.EmailLogEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailLog", ctx, id)
	ret0, _ := ret[0].(*entity.EmailLogEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailLog indicates an expected call of GetEmailLog.
func (mr *MockEmailRepositoryMockRecorder) GetEmailLog(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailLog", reflect.TypeOf((*MockEmailRepository)(nil).GetEmailLog), ctx, id)
}

// SaveEmailLog mocks base method.
func (m *MockEmailRepository) SaveEmailLog(ctx context.Context, to, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEmailLog", ctx, to, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEmailLog indicates an expected call of SaveEmailLog.
func (mr *MockEmailRepositoryMockRecorder) SaveEmailLog(ctx, to, subject, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEmailLog", reflect.TypeOf((*MockEmailRepository)(nil).SaveEmailLog), ctx, to, subject, body)
}
