// Code generated by MockGen. DO NOT EDIT.
// Source: backend/repository/interfaces/invoice.repository_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	entity "github.com/kamil5b/clean-go-vite-react/backend/model/entity"
)

// MockInvoiceRepository is a mock of InvoiceRepository interface.
type MockInvoiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceRepositoryMockRecorder
}

// MockInvoiceRepositoryMockRecorder is the mock recorder for MockInvoiceRepository.
type MockInvoiceRepositoryMockRecorder struct {
	mock *MockInvoiceRepository
}

// NewMockInvoiceRepository creates a new mock instance.
func NewMockInvoiceRepository(ctrl *gomock.Controller) *MockInvoiceRepository {
	mock := &MockInvoiceRepository{ctrl: ctrl}
	mock.recorder = &MockInvoiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceRepository) EXPECT() *MockInvoiceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvoiceRepository) Create(ctx context.Context, invoice entity.InvoiceEntity) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invoice)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInvoiceRepositoryMockRecorder) Create(ctx, invoice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvoiceRepository)(nil).Create), ctx, invoice)
}

// Delete mocks base method.
func (m *MockInvoiceRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvoiceRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvoiceRepository)(nil).Delete), ctx, id)
}

// DeleteInvoiceItems mocks base method.
func (m *MockInvoiceRepository) DeleteInvoiceItems(ctx context.Context, invoiceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvoiceItems", ctx, invoiceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvoiceItems indicates an expected call of DeleteInvoiceItems.
func (mr *MockInvoiceRepositoryMockRecorder) DeleteInvoiceItems(ctx, invoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvoiceItems", reflect.TypeOf((*MockInvoiceRepository)(nil).DeleteInvoiceItems), ctx, invoiceID)
}

// DeleteInvoiceTags mocks base method.
func (m *MockInvoiceRepository) DeleteInvoiceTags(ctx context.Context, invoiceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvoiceTags", ctx, invoiceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvoiceTags indicates an expected call of DeleteInvoiceTags.
func (mr *MockInvoiceRepositoryMockRecorder) DeleteInvoiceTags(ctx, invoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvoiceTags", reflect.TypeOf((*MockInvoiceRepository)(nil).DeleteInvoiceTags), ctx, invoiceID)
}

// FindAll mocks base method.
func (m *MockInvoiceRepository) FindAll(ctx context.Context, page, limit int, search string) ([]entity.InvoiceEntity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, page, limit, search)
	ret0, _ := ret[0].([]entity.InvoiceEntity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockInvoiceRepositoryMockRecorder) FindAll(ctx, page, limit, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockInvoiceRepository)(nil).FindAll), ctx, page, limit, search)
}

// FindByID mocks base method.
func (m *MockInvoiceRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.InvoiceEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.InvoiceEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockInvoiceRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockInvoiceRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockInvoiceRepository) Update(ctx context.Context, id uuid.UUID, invoice entity.InvoiceEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInvoiceRepositoryMockRecorder) Update(ctx, id, invoice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvoiceRepository)(nil).Update), ctx, id, invoice)
}
